Disable typeguard checking due to problems with numba
Numba is not generally able to compile arbitrary Python code.

Get this typeguard error in function _get_vals_jit:
numba.core.errors.TypingError: Failed in nopython mode pipeline
(step: nopython frontend).

See also: https://github.com/numba/numba/issues/6612
and numba supported python constructs:
https://numba.readthedocs.io/en/stable/reference/pysupported.html